# 旁白（英文，一字不改）+ 中文字幕。id 形如 "段.句"
SECTIONS = [
 ("0", [
  ("0.1","Late last year, Microsoft's CEO said something strange.","去年年底，微软的 CEO 说了一句奇怪的话。"),
  ("0.2","His company may have a bunch of AI chips sitting in inventory — that it can't plug in.","他们可能有一大批 AI 芯片躺在库存里，插不上电。"),
  ("0.3","The chips weren't the problem. The problem, in his words, was power.","问题不在芯片。用他的话说，问题在电。"),
  ("0.4","So today's question: will electricity become the ceiling on AI?","所以今天的问题是：电，会不会成为 AI 的天花板？"),
  ("0.5","My answer is yes. But not in the way you think.","我的答案是：会。但不是你想的那种方式。")]),
 ("1", [
  ("1.1","Start with the size of it.","先看规模。"),
  ("1.2","In 2024, data centers used about 415 terawatt-hours of electricity.","2024 年，全球数据中心用了大约 415 太瓦时的电。"),
  ("1.3","That's around one and a half percent of all the electricity the world uses.","大约占全世界用电量的 1.5%。"),
  ("1.4","One and a half percent doesn't sound like a crisis.","1.5%，听起来不像什么危机。"),
  ("1.5","But the International Energy Agency expects it to more than double by 2030, to around 945 terawatt-hours.","但国际能源署预计，到 2030 年这个数字会翻一倍多，达到约 945 太瓦时。"),
  ("1.6","That's slightly more than all of Japan uses today.","比整个日本今天的用电量还略多一点。"),
  ("1.7","And it's concentrated. The United States alone accounts for about 45 percent of data center electricity.","而且非常集中。光美国一家，就占了全球数据中心用电的约 45%。"),
  ("1.8","Through 2030, data centers are expected to drive nearly half of America's growth in electricity demand.","到 2030 年，美国新增的用电需求里，预计将近一半来自数据中心。")]),
 ("2", [
  ("2.1","Here's what most people miss.","但大多数人没注意到这一点。"),
  ("2.2","The world isn't running out of electricity. It's running out of time to connect it.","世界不是电不够了，而是来不及把电接过来。"),
  ("2.3","A data center is just a building. Feeding it takes a whole chain: power plants, transmission lines, transformers.","数据中心只是一栋楼。给它供电，需要一整条链：发电厂、输电线、变压器。"),
  ("2.4","And every link in that chain has a waiting line.","而这条链上的每一环，都在排队。"),
  ("2.5","New transmission lines in advanced economies take four to eight years to build.","在发达经济体，建一条新的输电线要 4 到 8 年。"),
  ("2.6","Large power transformers now have lead times of up to four years, and prices have jumped roughly 80 percent in five years.","大型变压器的交货期已经拉长到最多 4 年，价格五年里涨了大约 80%。"),
  ("2.7","Gas turbines? GE Vernova, one of the biggest makers, said late last year that it was sold out through 2028.","燃气轮机呢？最大的制造商之一 GE Vernova 去年年底说，2028 年以前的产能已经卖光了。"),
  ("2.8","The IEA estimates that, unless these bottlenecks are fixed, around 20 percent of planned data center projects could be delayed.","国际能源署估计，如果这些瓶颈解决不了，大约 20% 的在建数据中心项目可能延期。"),
  ("2.9","Morgan Stanley put a number on the gap: a shortfall of about 32 gigawatts for US data centers through 2028.","摩根士丹利算了一下缺口：到 2028 年，美国数据中心大约缺 32 吉瓦的电。"),
  ("2.10","That's roughly a third of what they need.","差不多是需求的三分之一。")]),
 ("3", [
  ("3.1","When something is scarce, its price tells you.","一样东西缺不缺，看价格就知道。"),
  ("3.2","PJM runs the power grid across all or parts of 13 US states and Washington, D.C.","PJM 负责管理美国 13 个州（全部或部分地区）加上华盛顿特区的电网。"),
  ("3.3","Every year, it holds an auction for future power supply.","它每年都会拍卖未来的供电能力。"),
  ("3.4","For 2024 to 2025, the price was about 29 dollars per megawatt-day.","2024 到 2025 年度，价格大约是每兆瓦每天 29 美元。"),
  ("3.5","For 2027 to 2028, it hit 333 dollars, the maximum the rules allowed.","到了 2027 到 2028 年度，价格涨到 333 美元，碰到了规则允许的上限。"),
  ("3.6","Analysts estimate that without the cap, it would have been close to 530.","分析师估计，如果没有上限，价格会接近 530 美元。"),
  ("3.7","And even at that price, the auction still fell short of its reliability target.","而且就算开出这个价，拍卖还是没凑够保障供电稳定所需的量。"),
  ("3.8","The reason? PJM's demand forecast jumped by 5,250 megawatts, almost entirely because of data centers.","原因呢？PJM 预测的用电需求一下子多了 5250 兆瓦，几乎全是因为数据中心。"),
  ("3.9","And that cost doesn't stay with tech companies.","而这笔钱，不只是科技公司在付。"),
  ("3.10","In Washington, D.C., one utility's residential customers saw bills rise about 21 dollars a month starting in June 2025, around 10 of it from these capacity prices.","在华盛顿特区，一家电力公司的居民用户从 2025 年 6 月起，电费每月涨了约 21 美元，其中约 10 美元来自这类容量价格。")]),
 ("4", [
  ("4.1","So the tech giants stopped waiting.","于是，科技巨头们不等了。"),
  ("4.2","Microsoft signed a deal to bring back a reactor at Three Mile Island, which shut down in 2019. It's now expected back online in 2027.","微软签了协议，让三哩岛一座 2019 年就关掉的核反应堆重新启动，现在预计 2027 年恢复发电。"),
  ("4.3","Others are skipping the grid entirely.","还有人干脆绕开电网。"),
  ("4.4","One analysis counted 59 US data center projects planning about 90 gigawatts of their own on-site power.","一份分析统计，美国有 59 个数据中心项目计划自建现场发电，总共约 90 吉瓦。"),
  ("4.5","That's more than a quarter of all planned data center capacity in the country.","这超过了全美规划中数据中心总容量的四分之一。"),
  ("4.6","And 92 percent of those projects were announced since the start of 2025.","而其中 92% 的项目，都是 2025 年以后才宣布的。"),
  ("4.7","It got strange. Crusoe, a company that builds AI data centers, ordered 29 gas turbines from Boom Supersonic, a startup best known for designing supersonic jets.","事情开始变得离奇。AI 数据中心建造商 Crusoe，向 Boom Supersonic 订了 29 台燃气轮机，而这家公司最出名的是设计超音速客机。"),
  ("4.8","Then, just last month, Crusoe walked away from that deal and turned to established suppliers like GE Vernova.","结果就在上个月，Crusoe 放弃了这笔订单，转向 GE Vernova 这样的老牌供应商。"),
  ("4.9","When time is the bottleneck, an untested machine is a risk few can afford.","当时间就是瓶颈，没被验证过的机器，是很少有人敢冒的险。")]),
 ("5", [
  ("5.1","Now flip the map.","现在，把地图翻过来。"),
  ("5.2","China generates more than twice as much electricity as the United States.","中国的发电量，是美国的两倍多。"),
  ("5.3","In 2025 alone, it added more than 430 gigawatts of wind and solar capacity.","光是 2025 年一年，中国就新增了超过 430 吉瓦的风电和光伏装机。"),
  ("5.4","BloombergNEF expects China to add more than six times as much generation capacity as the US over the next five years.","彭博新能源财经预计，未来五年，中国新增的发电装机将是美国的六倍多。"),
  ("5.5","One business school researcher put it simply: the US has the chips and is short on power. China has the power and is short on chips.","一位商学院的研究者说得很直白：美国有芯片、缺电；中国有电、缺芯片。"),
  ("5.6","So electricity isn't one ceiling. It's a different ceiling, depending on where you stand.","所以电不是一块天花板。站在哪里，天花板就不一样。")]),
 ("6", [
  ("6.1","So here's my call.","所以，我的判断是："),
  ("6.2","Electricity won't stop AI. Too much money is chasing this problem for that.","电挡不住 AI，追着这个问题砸的钱太多了。"),
  ("6.3","But for the next few years, power will decide three things: how fast AI grows, where it gets built, and who wins.","但未来几年，电会决定三件事：AI 长得多快、建在哪里，以及谁会赢。"),
  ("6.4","The winners won't just be the ones with the best models. They'll be the ones who locked in power early.","赢家不只是模型最好的那家，而是最早锁定电力的那家。"),
  ("6.5","I'd go further: by the end of this decade, a guaranteed grid connection may be worth more than the chips you plug into it.","我甚至觉得：到这个十年结束时，一个有保障的电网接口，可能比插在上面的芯片还值钱。")]),
 ("7", [
  ("7.1","What does this mean for you?","这和你有什么关系？"),
  ("7.2","If you live where data centers are booming, part of AI's bill may already be on your electricity bill.","如果你住在数据中心扎堆的地方，AI 的一部分账单，可能已经算进你的电费里了。"),
  ("7.3","And next time someone says AI is limited by chips, remember Microsoft's problem. The chips were there. The power wasn't.","下次再有人说 AI 卡在芯片上，想想微软的问题：芯片有了，电没有。"),
  ("7.4","So which do you think runs out first: chips, or electricity? Tell me in the comments.","那你觉得，芯片和电，哪个会先不够用？评论区告诉我。")]),
]
LINES = [dict(id=i, en=e, zh=z, sec=s) for s, ls in SECTIONS for (i, e, z) in ls]
# TTS 发音写法（只改读法，不改意思）
TTS_FIX = {
 "415 terawatt-hours":"four hundred fifteen terawatt-hours",
 "2024 to 2025":"twenty twenty-four to twenty twenty-five",
 "2027 to 2028":"twenty twenty-seven to twenty twenty-eight",
 "In 2024,":"In twenty twenty-four,",
 "945":"nine hundred forty-five",
 "by 2030":"by twenty thirty",
 "Through 2030":"Through twenty thirty",
 "through 2028":"through twenty twenty-eight",
 "In 2025 alone":"In twenty twenty-five alone",
 "since the start of 2025":"since the start of twenty twenty-five",
 "June 2025":"June twenty twenty-five",
 "shut down in 2019":"shut down in twenty nineteen",
 "in 2027":"in twenty twenty-seven",
 "5,250":"five thousand two hundred fifty",
 "430":"four hundred thirty",
 "GE Vernova":"G E Vernova",
 "PJM":"P J M",
 "IEA":"I E A",
 "BloombergNEF":"Bloomberg N E F",
 "D.C.":"D C",
 "to 530.":"to five thirty.",
 "333":"three thirty-three",
 "dollars per megawatt-day":"dollars per megawatt-day",
 "29 ":"twenty-nine ", "32 ":"thirty-two ", "59 ":"fifty-nine ", "90 ":"ninety ", "92 ":"ninety-two ", "13 ":"thirteen ", "21 ":"twenty-one ", "10 ":"ten ", "45 ":"forty-five ", "80 ":"eighty ", "20 ":"twenty ",
}
