# -*- coding: utf-8 -*-
"""旁白数据：英文逐字取自提示词，不得改动。
每行 = (id, [(英文块, 中文块), ...], 行前停顿秒数 或 None)
同一行内各英文块用空格连起来 == 原句。
"""

SEGMENTS = [
    ("0", "开头钩子"),
    ("1", "AI 看到的不是字"),
    ("2", "一次只做一件事"),
    ("3", "概率从哪里来"),
    ("4", "自动补全变成助手"),
    ("5", "学会先想再答"),
    ("6", "原来是这样"),
    ("7", "和你有什么关系"),
]

ROWS = [
    # ---- 段 0
    ("0.1", [("You've probably heard that AI just predicts the next word.", "你可能听说过：AI 只是在预测下一个词。")], 1.2),
    ("0.2", [("That's true.", "这没错。"), ("But it's also where most explanations stop.", "但大多数解释也就讲到这里为止。")], None),
    ("0.3", [("In September 2024, OpenAI tested two of its models on the AIME,", "2024 年 9 月，OpenAI 拿自己的两个模型去考 AIME，"),
             ("a hard American math competition.", "一场很难的美国数学竞赛。")], None),
    ("0.4", [("The older model, GPT-4o, solved about 12 percent of the problems.", "老模型 GPT-4o，只做对了大约 12% 的题。")], None),
    ("0.5", [("The newer one, called o1, solved 74 percent.", "新模型 o1，做对了 74%。")], None),
    ("0.6", [("Both of them still work by predicting the next word.", "两个模型靠的都还是预测下一个词。"),
             ("The difference is that one of them learned to think before it answers.", "区别在于，其中一个学会了先想再答。")], 0.6),
    # ---- 段 1
    ("1.1", [("Let's start with what the model actually sees.", "先看模型真正看到的是什么。"),
             ("Not letters. Not words. Numbers.", "不是字母，不是单词，是数字。")], 1.0),
    ("1.2", [("Your text gets chopped into pieces called tokens.", "你输入的文字，会被切成一块一块，叫作 token。")], None),
    ("1.3", [("In English, a token is about four characters,", "在英文里，一个 token 大约是 4 个字符，"),
             ("or roughly three quarters of a word.", "差不多是四分之三个单词。")], None),
    ("1.4", [("Each token is then swapped for an ID number.", "然后，每个 token 都会被换成一个编号。")], None),
    ("1.5", [("From here on, the model never sees your words again.", "从这一步开始，模型再也看不到你的字了，"),
             ("Only these numbers.", "只看得到这些数字。")], 0.5),
    ("1.6", [("That's why AI can stumble on things that feel trivial to us,", "所以 AI 可能会在一些我们觉得很简单的事上出错，"),
             ("like counting the letters in a word.", "比如数一个单词里有几个字母。"),
             ("It never saw the letters.", "因为它根本没看到过那些字母。")], None),
    # ---- 段 2
    ("2.1", [("So what does the model do with those numbers?", "那模型拿这些数字做什么？"),
             ("Just one job, over and over:", "只做一件事，一遍又一遍："),
             ("given everything so far, what comes next?", "根据前面所有内容，下一个是什么？")], 1.0),
    ("2.2", [("For every possible next token, it gives a probability.", "对每一个可能出现的下一个 token，它都会给出一个概率。")], None),
    ("2.3", [("After \"The cat sat on the,\" the word \"mat\" might score high,", "在 \"The cat sat on the\" 后面，\"mat\" 的概率可能很高，"),
             ("\"floor\" a bit lower, and \"banana\" almost zero.", "\"floor\" 低一点，\"banana\" 几乎为零。")], None),
    ("2.4", [("It picks one, adds it to the end, and asks the same question again.", "它选一个，接到末尾，然后再问同一个问题。")], None),
    ("2.5", [("Token by token,", "一个 token 接一个 token，"),
             ("that's how every answer you've ever gotten from a chatbot was built.", "你从聊天机器人那里得到的每一个回答，都是这样拼出来的。")], None),
    ("2.6", [("A long answer can take hundreds or even thousands of these predictions,", "一个长回答，可能要做几百甚至几千次这样的预测，"),
             ("each one depending on everything that came before it.", "每一次都取决于前面所有的内容。")], None),
    ("2.7", [("And it doesn't always pick the top choice.", "而且它不一定选概率最高的那个。"),
             ("A little randomness is usually built in,", "通常会加一点随机性，"),
             ("which is why the same question can get two different answers.", "所以同一个问题问两次，答案可能不一样。")], None),
    ("2.8", [("So far, this is the explanation you've heard before.", "到这里，都是你以前听过的解释。"),
             ("The interesting part is where those probabilities come from.", "真正有意思的，是这些概率从哪里来。")], 0.5),
    # ---- 段 3
    ("3.1", [("Inside the model are billions of numbers called parameters.", "模型里面有几十亿个数字，叫作参数。")], 1.0),
    ("3.2", [("GPT-3, back in 2020, had 175 billion of them.", "2020 年的 GPT-3，就有 1750 亿个。")], None),
    ("3.3", [("So how does it decide which earlier words matter?", "那它怎么判断前面哪些词重要？"),
             ("Inside, each token becomes a long list of numbers,", "在模型内部，每个 token 都会变成一长串数字，"),
             ("and those lists pass through layer after layer.", "这些数字一层一层地往上传。")], None),
    ("3.4", [("In each layer, every token can look back at the tokens before it,", "在每一层里，每个 token 都可以回头看前面的 token，"),
             ("and pull in the ones that are relevant.", "把相关的那些信息拉过来。")], None),
    ("3.5", [("Take this sentence: \"The cat sat on the mat because it was tired.\"", "比如这句话：\"The cat sat on the mat because it was tired.\"（猫坐在垫子上，因为它累了。）"),
             ("To make sense of \"it,\" the model has to connect it back to \"cat,\" not \"mat.\"", "要理解 \"it\"，模型得把它连回 \"cat\"，而不是 \"mat\"。")], None),
    ("3.6", [("This step is called attention.", "这一步叫作“注意力”。"),
             ("It comes from a 2017 paper by researchers at Google,", "它来自 2017 年谷歌研究者的一篇论文，"),
             ("titled \"Attention Is All You Need,\"", "题目就叫《Attention Is All You Need》，"),
             ("and it's the core of the design behind today's large language models.", "是今天大语言模型设计的核心。")], None),
    ("3.7", [("At the start, all those parameters are random,", "一开始，所有这些参数都是随机的，"),
             ("and the model's guesses are nonsense.", "模型猜出来的全是胡话。")], None),
    ("3.8", [("Training is a guessing game.", "训练就是一场猜词游戏："),
             ("Show the model real text, hide the next token, let it guess,", "给模型看真实的文字，把下一个 token 遮住，让它猜，"),
             ("then nudge every parameter slightly toward the right answer.", "然后把每个参数都往正确答案的方向轻轻推一点。")], None),
    ("3.9", [("Then do it again. And again.", "然后再来一次，再来一次。"),
             ("Meta's Llama 3 was trained on more than 15 trillion tokens.", "Meta 的 Llama 3，训练用了超过 15 万亿个 token。")], None),
    ("3.10", [("To put that in perspective:", "换个说法："),
              ("a person reading nonstop, at an average reading speed,", "一个人以正常速度不停地读，"),
              ("would need roughly 90,000 years to get through that much text.", "大约要读 9 万年才能读完这么多文字。")], 0.5),
    ("3.11", [("And here's the surprising part.", "意外的地方在这里："),
              ("To get good at guessing the next word across all that text,", "为了在这么多文字上都猜得准，"),
              ("the model ends up picking up grammar, facts,", "模型顺带学会了语法、事实，"),
              ("and patterns of reasoning along the way.", "还有推理的套路。")], None),
    ("3.12", [("Nobody programmed those in.", "没有人把这些写进程序。"),
              ("They're a side effect of getting good at guessing.", "它们是“猜得准”的副产品。")], 0.5),
    # ---- 段 4
    ("4.1", [("But a model trained only this way has a strange problem.", "但只这样训练出来的模型，有个奇怪的毛病。")], 1.0),
    ("4.2", [("It's an autocomplete for the internet.", "它是一台“互联网自动补全机”。"),
             ("Ask it a question, and it might just write more questions,", "你问它一个问题，它可能接着写出更多问题，"),
             ("the way a quiz or a homework sheet would carry on.", "就像一张测验卷或作业纸会一直往下列题。")], None),
    ("4.3", [("Turning it into an assistant takes a second, much smaller round of training.", "要把它变成助手，还需要第二轮训练，规模小得多。")], None),
    ("4.4", [("People write example answers and rank the model's replies,", "人先写出示范回答，再给模型的回答排名次，"),
             ("and the model is tuned toward the ones people prefer.", "然后把模型往人更喜欢的方向调。")], None),
    ("4.5", [("Ranking is the clever part.", "排名次是最巧的地方："),
             ("It's much easier for a person to say which of two answers is better", "让人说出两个回答哪个更好，"),
             ("than to write the perfect answer themselves.", "比让人自己写出完美的回答容易得多。")], None),
    ("4.6", [("In 2022, OpenAI showed how powerful this step is.", "2022 年，OpenAI 证明了这一步有多厉害："),
             ("People preferred answers from a 1.3 billion parameter model trained this way", "经过这种训练的 13 亿参数模型，"),
             ("over the 175 billion parameter GPT-3.", "回答比 1750 亿参数的 GPT-3 更受人喜欢。")], None),
    ("4.7", [("A model more than 100 times smaller, and people liked it better.", "小了一百多倍，人们却更喜欢它。")], 0.5),
    ("4.8", [("By 2023, that was the full story:", "到了 2023 年，故事就是这样："),
             ("predict the next word, then get polished by human feedback.", "先学会预测下一个词，再靠人的反馈打磨。")], None),
    ("4.9", [("Then the story changed.", "然后，故事变了。")], 0.8),
    # ---- 段 5
    ("5.1", [("Remember those math scores?", "还记得那两个数学成绩吗？"),
             ("12 percent versus 74.", "12% 对 74%。")], 1.0),
    ("5.2", [("The key new ingredient was a different kind of training,", "关键的新东西是另一种训练，"),
             ("called reinforcement learning.", "叫强化学习。"),
             ("OpenAI hasn't published the details,", "OpenAI 没公开细节，"),
             ("but here's the basic idea, as other labs have since described it.", "但其他实验室后来公开过基本做法，是这样的：")], None),
    ("5.3", [("Give the model a math problem.", "给模型一道数学题，"),
             ("Let it write out as much working as it wants before its final answer.", "让它在给出最终答案之前，想写多少推演就写多少。")], None),
    ("5.4", [("If the answer is right, reward it.", "答对了就奖励，"),
             ("If it's wrong, don't.", "答错了就不奖励。")], None),
    ("5.5", [("Nobody shows it how to reason.", "没有人教它怎么推理，"),
             ("It only finds out whether it got the answer right.", "它只知道自己最后答没答对。")], None),
    ("5.6", [("In January 2025, the Chinese lab DeepSeek published", "2025 年 1 月，中国公司 DeepSeek 公开了"),
             ("what happened when they trained a model this way.", "他们用这种方法训练模型的结果。")], None),
    ("5.7", [("On that same math competition,", "在同一场数学竞赛上，"),
             ("the model's score climbed from 15.6 percent to 71 percent", "模型的分数从 15.6% 涨到了 71%，"),
             ("over the course of training.", "在训练过程中。")], None),
    ("5.8", [("And it started doing things nobody had taught it.", "而且它开始做一些没人教过它的事："),
             ("It spent longer thinking on each problem.", "每道题想得越来越久，"),
             ("It went back and checked its own steps.", "还会回头检查自己的步骤。")], None),
    ("5.9", [("At one point, in the middle of a solution, it wrote:", "有一次解题解到一半，它写下："),
             ("\"Wait, wait. Wait.\"", "\"Wait, wait. Wait.\"（等等，等等。等一下。）"),
             ("Then it found its own mistake.", "然后它找到了自己的错误。")], 0.5),
    ("5.10", [("The researchers called it an \"aha moment.\"", "研究者把这叫作“顿悟时刻”。")], 0.6),
    ("5.11", [("By the spring of 2025, OpenAI, DeepSeek, Anthropic and Google", "到 2025 年春天，OpenAI、DeepSeek、Anthropic 和谷歌"),
              ("had all released models that can think before they answer.", "都已经推出了会先想再答的模型。")], None),
    ("5.12", [("And OpenAI reported something else:", "OpenAI 还发现了一件事："),
              ("the longer the model is allowed to think, the better it tends to do.", "允许模型想得越久，它往往做得越好。")], None),
    ("5.13", [("That's what is happening when a chatbot pauses", "当聊天机器人停下来、"),
              ("and shows you a \"thinking\" label.", "显示“正在思考”的时候，发生的就是这件事："),
              ("It's writing out its working before it shows you the answer.", "它在给你答案之前，先把推演写出来。")], None),
    ("5.14", [("And that working isn't free.", "而这些推演不是免费的。"),
              ("Every thinking token has to be predicted, just like the answer.", "每一个“思考”的 token 都要像答案一样被预测出来。"),
              ("On OpenAI's API, those reasoning tokens are billed as output,", "在 OpenAI 的 API 上，这些推理 token 和答案一样按输出计费，"),
              ("even though you never see them.", "哪怕你根本看不到它们。")], None),
    ("5.15", [("That's why thinking mode is slower,", "所以思考模式更慢，"),
              ("and why it often costs more.", "也常常更贵。")], None),
    # ---- 段 6
    ("6.1", [("So here's the part most explanations miss.", "所以，大多数解释漏掉的是这一点。")], 1.0),
    ("6.2", [("AI still just predicts the next word.", "AI 还是只在预测下一个词。"),
             ("That never changed.", "这一点从来没变。")], 0.5),
    ("6.3", [("What changed is what it's predicting.", "变的是它在预测什么："),
             ("Not just what someone on the internet would write next,", "不只是网上的人下一句会写什么，"),
             ("but the steps that lead to a right answer.", "而是通往正确答案的那些步骤。")], None),
    ("6.4", [("The thinking is made of the same tokens, one at a time.", "那些“思考”，也是由同样的 token 一个一个组成的。"),
             ("It's next-word prediction, pointed at a goal.", "它还是在预测下一个词，只是有了目标。")], None),
    ("6.5", [("So the whole recipe has three stages.", "所以整套做法分三步："),
             ("First, guess the next word across trillions of tokens.", "第一，在几万亿个 token 上猜下一个词；"),
             ("Second, get polished by human preferences.", "第二，按人的喜好打磨；"),
             ("Third, get rewarded for reaching right answers.", "第三，答对了就奖励。")], None),
    ("6.6", [("Most explanations stop after the first two.", "大多数解释讲完前两步就停了。"),
             ("The third is the one that changed what AI can do.", "真正改变 AI 能力的，是第三步。")], 0.6),
    # ---- 段 7
    ("7.1", [("What does this mean for you?", "这和你有什么关系？")], 1.0),
    ("7.2", [("First, for hard problems, like math, code, or planning,", "第一，遇到难题，比如数学、写代码、做计划，"),
             ("use the thinking mode if your AI has one.", "如果你的 AI 有思考模式，就打开它。"),
             ("It's the same kind of machine, given time to think.", "还是同一类机器，只是给了它思考的时间。")], None),
    ("7.3", [("Second, thinking isn't the same as knowing.", "第二，会思考不等于知道。"),
             ("Its knowledge still comes from patterns in its training,", "它的知识还是来自训练里学到的规律，"),
             ("so it can reason carefully and still be wrong.", "所以它可能推得很认真，结果还是错的。"),
             ("Check anything that matters.", "重要的事，自己核实一下。")], None),
    ("7.4", [("So here's my question.", "最后问你一个问题："),
             ("When an AI writes \"wait, let me check that,\" is it really thinking?", "当 AI 写下“等等，我检查一下”的时候，它是真的在思考，"),
             ("Or is it just a very good prediction of what thinking looks like?", "还是只是非常擅长预测“思考看起来是什么样子”？"),
             ("Tell me in the comments.", "评论区告诉我。")], 0.6),
]

# 只改读法，不改意思。按顺序替换。
import re
TTS_SUBS = [
    (r"GPT-4o", "G P T four oh"),
    (r"GPT-3", "G P T three"),
    (r"\bo1\b", "oh one"),
    (r"\bAIME\b", "A I M E"),
    (r"\bAPI\b", "A P I"),
    (r"\bAI\b", "A I"),
    (r"\bID\b", "I D"),
    (r"1\.3 billion", "one point three billion"),
    (r"15\.6 percent", "fifteen point six percent"),
    (r"175 billion", "one hundred seventy-five billion"),
    (r"15 trillion", "fifteen trillion"),
    (r"90,000", "ninety thousand"),
    (r"100 times", "one hundred times"),
    (r"\b12 percent", "twelve percent"),
    (r"\b74 percent", "seventy-four percent"),
    (r"\b71 percent", "seventy-one percent"),
    (r"versus 74\.", "versus seventy-four."),
    (r"Llama 3", "Llama three"),
    (r"\b2017\b", "twenty seventeen"),
    (r"\b2020\b", "twenty twenty"),
    (r"\b2022\b", "twenty twenty-two"),
    (r"\b2023\b", "twenty twenty-three"),
    (r"\b2024\b", "twenty twenty-four"),
    (r"\b2025\b", "twenty twenty-five"),
]


def tts_text(s):
    for pat, rep in TTS_SUBS:
        s = re.sub(pat, rep, s)
    return s.replace("“", '"')
